version: "3.9"
services:
  tgbot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.025'
          memory: 100M
